### ISSUE TITLE
Message "Couldn't start client Svelte" inside a remote container

### ISSUE THREAD

**Issue by akkie** [sveltejs/language-tools#1340]
**Describe the bug**
When using a svelte project inside a remote container, VSCode shows the message "Couldn't start client Svelte". Nothing expect  syntax highlighting works. If I run the same project locally, all works as expected.

**To Reproduce**

The config for my dev container:

### .devcontainer.json
```json
{
    "name": "App",
    "dockerComposeFile": ["./docker-compose.yml"],
    "service": "node",
	"extensions": [
		"dbaeumer.vscode-eslint",
		"ms-azuretools.vscode-docker",
		"svelte.svelte-vscode",
		"csstools.postcss",
		"bradlc.vscode-tailwindcss",
		"k--kato.intellij-idea-keybindings",
		"visualstudioexptteam.vscodeintellicode"
	],
	"settings": {
		"terminal.integrated.defaultProfile.linux": "bash",
	},
	"postCreateCommand": "yarn install",
	"remoteUser": "node",
	"workspaceFolder": "/home/node/app",
}
```

### .docker-compose.yml
```yaml
version: '3'
services:
  node:
    container_name: node
    build: .
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - 3000:3000
      - 15000:15000
    volumes:
      - ../:/home/node/app:cached
      - $HOME/.ssh:/home/node/.ssh
```
### Dockerfile
```
FROM mcr.microsoft.com/vscode/devcontainers/typescript-node:16-bullseye
```

**Expected behavior**
It should be possible to use the svelte VSCode extension in a remote container.

**Screenshots**
<img width="474" alt="svelte-client-error" src="https://user-images.githubusercontent.com/307006/149810534-4e6f33b7-35d5-41e7-8ff3-fe81cef2e590.png">
>

**System (please complete the following information):**
 - OS: macOS Monterey
 - IDE: VSCode
 - Plugin/Package: "Svelte for VSCode"
