### ISSUE TITLE
How to disable or change style autoformat on vscode?

### ISSUE THREAD

**Issue by dominggo1999** [sveltejs/language-tools#1492]
I am using tailwind @apply in my svelte file like this 

```css
 .title {
    @apply text-red-500;
 }
```

It's not a problem if I am not using a lot of tailwind classes. But if I need more complex styling , it will become hard to read in one line, so I will write something like this to improve readibility :

```css
 .title {
    @apply 
        flex 
        items-center
        font-bold
        text-3xl
        uppercase
        dark:text-accent;
 }
```
The problem is svelte vscode formatter will format it again into one line. Is there any setting i can tweak to prevent auto-format or change formatting settings?
