### ISSUE TITLE
svelte-check: unknown css-property print-color-adjust

### ISSUE THREAD

**Issue by mrtronje** [sveltejs/language-tools#1661]
### Describe the bug

If I run svelte-check i get this warning 
```
 Warn: Unknown property: 'print-color-adjust' (scss)
```
But actually it's not an unknown property (https://developer.mozilla.org/en-US/docs/Web/CSS/print-color-adjust). Is there a way to ignore this warning at least? Can I configure something to get rid of this error or do I have the possability to ignore this line directly in code, like
```scss
.my-class {
    // svelte-check-ignore
    print-color-adjust: exact;
}
```

### Reproduction

   ```scss
    .my-class {
        print-color-adjust: exact;
        -webkit-print-color-adjust: exact;
    }
  ```

### Expected behaviour

A way to ignore specific warnings or not throwing this warning

### System Info

- OS: Manjarro
- svelte-check 2.9.0

### Which package is the issue about?

svelte-check
