### ISSUE TITLE
Sort CSS on save

### ISSUE THREAD

**Issue by janosh** [sveltejs/language-tools#1714]
### Description

I occasionally write repeated CSS rules by accident

```css
:where(aside.some-class.desktop) {
    background: rgba(255, 255, 255, 0.2);
    border-radius: 5pt;
    border: none;
    bottom: 0;
    color: black;
    cursor: pointer;
    font-size: 2em;
    line-height: 0;
    padding: 2pt 4pt;
    position: absolute;
    right: 0;
    z-index: 2;
    border-radius: 4pt;
}
```

In this block `border-radius` appears twice but isn't easy to spot. Rules are faster to search by eye when sorted alphabetically.

### Proposed solution

Sort CSS rules within each block.

### Alternatives

Just a suggestion, feel free to close as not planned.

### Additional Information, eg. Screenshots

There appear to be unmaintained VS Code extensions that do this:

1. https://github.com/mrmlnc/vscode-postcss-sorting ([marketplace](https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-postcss-sorting))
2. https://github.com/mattkenefick/vscode-css-alphabetize ([marketplace](https://marketplace.visualstudio.com/items?itemName=PolymerMallard.css-alphabetize))

**Comment by cooolbros** [comment]
What if the language-tools warned of duplicate CSS properties?

**Comment by janosh** [comment]
@cooolbros There's already `css.lint.duplicateProperties` ([VS Code docs](https://code.visualstudio.com/Docs/languages/CSS#_customizing-css-scss-and-less-settings)) which helps with that but would be nice to also sort alphabetically for faster screening of blocks.

**Comment by janosh** [comment]
Afaict, neither extension supports sorting on save.

**Comment by jasonlyu123** [comment]
I don't think it can be reliably achieved because the CSS property order matters in how they're applied. 

For example:

if we sort this by property name
```css
	h1 {
		background-color: green;
		background: red;
	}
```

it would become:
```css
	h1 {
		background: red;
		background-color: green;
	}
```

That will change which CSS got applied. The other alternative is that VSCode can provide a quick fix to remove duplicated properties.
