### ISSUE TITLE
Q: How to edit Svelte for VS Code to refine CSS diagnostic messages for tailwind support?

### ISSUE THREAD

**Issue by paul42** [sveltejs/language-tools#461]
I'm using tailwind with svelte, and I'd like to improve how it handles css error messages. How can I make a pull request to vs-code extension `Svelte for VS Code` to suppress this error, or allow for tailwind-style multiple class entries like below? 
Is this eslint based?

Example CSS causing error is last line with `@apply`
```css
h1 {
    color: #ff3e00;
    text-transform: uppercase;
    font-size: 4em;
    font-weight: 100;
    @apply bg-black text-white;
  }
```

current workaround to avoid red squiggly lines is to go into the extension settings and set:
```json
{
    "svelte.plugin.css.diagnostics.enable": true
}
```

Thanks in advance. I love the plugin so I'd love to be able to help out if possible :D
