### ISSUE TITLE
Writes random jumble on save when an error exists

### ISSUE THREAD

**Issue by Karitham** [sveltejs/language-tools#970]
**Describe the bug**
Sometimes, when saving, the lsp writes seemingly random stuff where there is an error,
The text is written before the lsp recognises that the error is fixed, so it creates and error and writes again. 

**To Reproduce**
Have an error, spam save, (works on my end)

```js
            <button class="btn-icon delete">
              <Icon data="{icons.trash}" />
            </button>
```
turns into
```js
            <button class="btn-icon delete">
              <Icon data="{icons.rashtrrrrrr}" />
            </button>
```

**Expected behavior**
Not writing anything and/or waiting to complete analysis before doing so

**Screenshots**
![example 1](https://media.discordapp.net/attachments/281216402684116993/836515577248874536/unknown.png)
![example 2](https://cdn.discordapp.com/attachments/281216402684116993/836508387822796821/unknown.png)

After a few saves, the example 2 turns into
![example 3](https://cdn.discordapp.com/attachments/287739410286379019/836511075653779466/unknown.png)

*before saving*
![example before saving](https://cdn.discordapp.com/attachments/806273355526963283/836519654755008582/unknown.png)
*after saving*
![example after saving](https://cdn.discordapp.com/attachments/806273355526963283/836519819447894046/unknown.png)

**System (please complete the following information):**
 - OS: Linux (5.11.16-arch1-1)
 - IDE: VSCode
 - Plugin/Package: "Svelte for VSCode" - v104.10.2
 
**Additional context**
The only way to work around this issue is to kill the lsp, write and save before it completly starts, and then it works fine until the bugs appears again.

I don't really understand how this works. With logging to verbose, the extension logs
```yaml
[Trace - 10:12:53] Sending request 'textDocument/codeAction - (959)'.
Params: {
    "textDocument": {
        "uri": "file:///home/karitham/Projects/STM/Front/src/components/Table/Table.svelte"
    },
    "range": {
        "start": {
            "line": 79,
            "character": 44
        },
        "end": {
            "line": 79,
            "character": 44
        }
    },
    "context": {
        "diagnostics": []
    }
}
```
for the example 1 (the first picture)
